on: [push]

jobs:
  self_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        run: |
          wget -O- https://nodejs.org/dist/v14.21.3/node-v14.21.3-linux-x64.tar.xz | tar -Jx
      - name: Self-testing
        uses: second-state/wasmedge-actions-libsodium-tests@main
        with:
          path: node-v14.21.3-linux-x64/bin
          wasi-runtime: node
